/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="@openeth/truffle-typings" />
import BN from "bn.js";

export interface DefaultConstructorContract extends Truffle.Contract<DefaultConstructorInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<DefaultConstructorInstance>;
}

export interface DumbContractContract extends Truffle.Contract<DumbContractInstance> {
  "new"(
    _counter: number | BN | string,
    meta?: Truffle.TransactionDetails,
  ): Promise<DumbContractInstance>;
}

export interface MigrationsContract extends Truffle.Contract<MigrationsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<MigrationsInstance>;
}

export interface DefaultConstructorInstance extends Truffle.ContractInstance {
  counter(txDetails?: Truffle.TransactionDetails): Promise<BN>;
}

export interface DumbContractInstance extends Truffle.ContractInstance {
  arrayParamLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  someAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  counter(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  counterArray(arg0: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  SOME_VALUE(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  byteArray(txDetails?: Truffle.TransactionDetails): Promise<string>;

  counterWithOffset(
    offset: number | BN | string,
    txDetails?: Truffle.TransactionDetails,
  ): Promise<BN>;

  returnAll(txDetails?: Truffle.TransactionDetails): Promise<[BN, BN]>;

  returnAllTypesStruct(
    txDetails?: Truffle.TransactionDetails,
  ): Promise<{
    counter: string;
    someBool: boolean;
    counterArray: string[];
    someAddress: string;
    byte32Array: string;
    bytesArray: string;
  }>;

  countup: {
    (offset: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(offset: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      offset: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<string>;
    estimateGas(
      offset: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<number>;
  };

  countupWithReturn: {
    (offset: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(offset: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<BN>;
    sendTransaction(
      offset: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<string>;
    estimateGas(
      offset: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<number>;
  };

  returnSigned(offset: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  countupForEther: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  twoUnnamedArgs: {
    (
      arg0: number | BN | string,
      arg1: number | BN | string,
      ret: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<Truffle.TransactionResponse>;
    call(
      arg0: number | BN | string,
      arg1: number | BN | string,
      ret: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<BN>;
    sendTransaction(
      arg0: number | BN | string,
      arg1: number | BN | string,
      ret: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<string>;
    estimateGas(
      arg0: number | BN | string,
      arg1: number | BN | string,
      ret: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<number>;
  };

  callWithArray(
    arrayParam: (number | BN | string)[],
    txDetails?: Truffle.TransactionDetails,
  ): Promise<BN[]>;

  callWithBytes(byteParam: string | BN, txDetails?: Truffle.TransactionDetails): Promise<string>;

  testAddress(a: string | BN, txDetails?: Truffle.TransactionDetails): Promise<string>;

  testString(a: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
}

export interface MigrationsInstance extends Truffle.ContractInstance {
  last_completed_migration(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  setCompleted: {
    (completed: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(completed: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      completed: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<string>;
    estimateGas(
      completed: number | BN | string,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<number>;
  };

  upgrade: {
    (new_address: string | BN, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(new_address: string | BN, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      new_address: string | BN,
      txDetails?: Truffle.TransactionDetails,
    ): Promise<string>;
    estimateGas(new_address: string | BN, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}
